[tool.poetry]
name = "hw-10-1"
version = "0.1.0"
description = ""
authors = ["dr.Alexander Vasilenko <vasilenko8021978@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
mypy = "^1.19.1"
black = "^26.1.0"
isort = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
